# Reducir mapa


In [9]:
# Importamos los paquetes requeridos
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

%matplotlib inline 
plt.rcParams['figure.figsize'] = 16, 16

ImportError: this version of pandas is incompatible with numpy < 1.15.4
your numpy version is 1.15.2.
Please upgrade numpy to >= 1.15.4 to use this pandas version

In [14]:
# Este archivo contiene la información acerca del mapa.
filename = 'colliders.csv'
data = np.loadtxt(filename, delimiter=',', dtype='Float64', skiprows=2)
print(len(data))
print(data)

3845
[[-310.2389   -439.2315     85.5         5.          5.         85.5     ]
 [-300.2389   -439.2315     85.5         5.          5.         85.5     ]
 [-290.2389   -439.2315     85.5         5.          5.         85.5     ]
 ...
 [ 257.8061    425.1645      1.75852     1.292725    1.292725    1.944791]
 [ 293.9967    368.3391      3.557666    1.129456    1.129456    3.667319]
 [ 281.5162    354.4156      4.999351    1.053772    1.053772    4.950246]]


In [10]:
# set new values


xmin = np.min(data[:, 0] - data[:, 3])
xmax = np.max(data[:, 0] + data[:, 3])

ymin = np.min(data[:, 1] - data[:, 4])
ymax = np.max(data[:, 1] + data[:, 4])

zmin = 0
# Limit the z axis for the visualization
zmax = 10

print("X")
print("min = {0}, max = {1}\n".format(xmin, xmax))

print("Y")
print("min = {0}, max = {1}\n".format(ymin, ymax))

print("Z")
print("min = {0}, max = {1}".format(zmin, zmax))




X
min = -315.2389, max = 604.7611

Y
min = -444.2315, max = 475.7685

Z
min = 0, max = 10


In [20]:
r_max_north = 300
r_min_north = -300
r_max_east = 400
r_min_east = -100

In [21]:
new_data = []
for i in range(data.shape[0]):
    north, east, alt, d_north, d_east, d_alt = data[i, :]
    if north > r_min_north and north < r_max_north and east > r_min_east and east < r_max_east:
        new_data.append(data[i])
new_data = np.array(new_data)

In [23]:
print(len(new_data))
print(new_data)

1346
[[-270.2389    -99.23154    80.          5.          5.         80.      ]
 [-260.2389    -99.23153    80.          5.          5.         80.      ]
 [-250.2389    -99.23155    80.00001     5.          5.         80.00001 ]
 ...
 [ 252.053     368.9957      3.065603    1.407089    1.407104    3.16009 ]
 [ 293.9967    368.3391      3.557666    1.129456    1.129456    3.667319]
 [ 281.5162    354.4156      4.999351    1.053772    1.053772    4.950246]]


In [24]:
np.savetxt('data_reduced.csv', new_data, delimiter=',')